# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

type: object
additionalProperties: false
required:
  - docker
  - k8s
  - extensions
  - authentication
  - prometheus
  - database
  - initial
  - logging
  - requests
properties:
  docker:
    type: object
    additionalProperties: false
    required:
      - registry
      - externalRegistry
    properties:
      registry:
        type: string
      externalRegistry:
        type: string
  k8s:
    type: object
    additionalProperties: false
    required:
      - storageClassName
      - storageAccessMode
      - promtail
      - namespace
    properties:
      storageClassName:
        type: string
      storageAccessMode:
        type: string
        enum:
          - ReadWriteOnce
          - ReadOnlyMany
          - ReadWriteMany
          - ReadWriteOncePod
      cluster:
        type: object
        additionalProperties: false
        properties:
          imagePullPolicy:
            type: string
            enum:
              - Always
              - IfNotPresent
              - Never
          podSecurityContext:
            type: object
            additionalProperties: false
            properties:
              runAsUser:
                type: number
              runAsGroup:
                type: number
              fsGroup:
                type: number
              runAsNonRoot:
                type: boolean
      promtail:
        type: object
        additionalProperties: false
        required:
          - lokiEnabled
        properties:
          lokiEnabled:
            type: boolean
          lokiUrl:
            type:
              - string
          lokiUsername:
            type:
              - string
          lokiPassword:
            type:
              - string
          serverPort:
            type:
              - number
        anyOf:
          - properties:
              lokiEnabled:
                const: false
          - required:
              - lokiUrl
              - lokiUsername
              - lokiPassword
              - serverPort
      namespace:
        type: string
      context:
        type: string
      ingressClassName:
        type: string
  general:
    type: object
    additionalProperties: false
    required:
      - host
      - port
      - scheme
    properties:
      host:
        type: string
      port:
        type: string
      scheme:
        type: string
      metadata:
        type: object
        properties:
          privacyPolicyURL:
            type: string
          imprintURL:
            type: string
          provider:
            type: string
          authenticationProvider:
            type: string
          environment:
            type: string
  extensions:
    type: object
    additionalProperties: false
    required:
      - guacamole
    properties:
      guacamole:
        type: object
        additionalProperties: false
        required:
          - baseURI
          - publicURI
          - username
          - password
        properties:
          baseURI:
            type: string
          publicURI:
            type: string
          username:
            type: string
          password:
            type: string
      jupyter:
        type: object
        additionalProperties: false
        required:
          - publicURI
        properties:
          publicURI:
            type: string
  authentication:
    type: object
    required:
      - provider
    oneOf:
      - type: object
        additionalProperties: false
        required:
          - oauth
          - jwt
        properties:
          provider:
            const: oauth
          oauth:
            type: object
            additionalProperties: false
            required:
              - endpoints
              - audience
              - scopes
              - client
              - redirectURI
            properties:
              endpoints:
                type: object
                additionalProperties: false
                properties:
                  tokenIssuance:
                    type:
                      - string
                      - "null"
                  authorization:
                    type:
                      - string
                      - "null"
                  wellKnown:
                    type:
                      - string
                      - "null"
              audience:
                type: string
              scopes:
                type:
                  - array
                  - "null"
                items:
                  type: string
                  enum:
                    - openid
              client:
                type: object
                additionalProperties: false
                required:
                  - id
                  - secret
                properties:
                  id:
                    type: string
                  secret:
                    type:
                      - string
                      - "null"
              redirectURI:
                type: string
          jwt:
            type: object
            additionalProperties: false
            properties:
              usernameClaim:
                type: string
      - type: object
        additionalProperties: false
        required:
          - azure
          - jwt
        properties:
          provider:
            const: azure
          azure:
            type: object
            additionalProperties: false
            required:
              - authorizationEndpoint
              - client
              - redirectURI
            properties:
              authorizationEndpoint:
                type: string
              client:
                type: object
                additionalProperties: false
                required:
                  - id
                  - secret
                properties:
                  id:
                    type: string
                  secret:
                    type: string
              redirectURI:
                type: string
          jwt:
            type: object
            additionalProperties: false
            properties:
              usernameClaim:
                type: string
  prometheus:
    type: object
    additionalProperties: false
    required:
      - url
    properties:
      url:
        type: string
  database:
    type: object
    additionalProperties: false
    required:
      - url
    properties:
      url:
        type: string
  initial:
    type: object
    additionalProperties: false
    required:
      - admin
    properties:
      admin:
        type: string
  logging:
    type: object
    additionalProperties: false
    required:
      - level
      - logPath
    properties:
      logPath:
        type: string
      level:
        type: string
        enum:
          - CRITICAL
          - ERROR
          - WARNING
          - INFO
          - DEBUG
          - NOTSET
  requests:
    type: object
    additionalProperties: false
    required:
      - timeout
    properties:
      timeout:
        type: number
  pipelines:
    type: object
    additionalProperties: false
    properties:
      timeout:
        type: number
