# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

site_name: Capella Collaboration Manager Documentation
theme:
  name: material
nav:
  - Introduction: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Introduction to Capella: getting-started/capella-intro.md
  - Projects:
      - Get access to a project: projects/access.md
      - Add a user to a project: projects/add-user.md
      - Request a new project: projects/create.md
      - Delete a project: projects/delete.md
      - Roles: projects/roles.md
      - Models:
          - Create a model: projects/models/create.md
          - Update a model to a newer version: projects/models/update.md
          - Update model metadata: projects/models/metadata.md
          - Model sources:
              - TeamForCapella: projects/models/sources/t4c.md
          - Backups:
              - Setup a model backup: projects/models/backups/setup.md
              - Trigger a model backup: projects/models/backups/trigger.md
              - Remove a model backup: projects/models/backups/remove.md
          - Diagram cache:
              - Setup diagram cache: projects/models/diagrams/setup_diagram_cache.md
              - View diagram cache: projects/models/diagrams/view_diagram_cache.md
          - Model complexity badge: projects/models/complexity_badge.md
  - Sessions:
      - Session Types:
          - Overview: sessions/types.md
          - Persistent: sessions/types/persistent.md
          - Read-Only: sessions/types/read-only.md
      - Request Session: sessions/request.md
      - (Re-)Connect to Session: sessions/reconnect.md
      - Terminate Session: sessions/terminate.md
      - Taking Screenshots: sessions/screenshot/screenshots.md
      - Flows:
          - Git: sessions/flows/git.md
          - TeamForCapella: sessions/flows/t4c.md
      - Files (Upload): sessions/files/files.md
      - Troubleshooting: sessions/troubleshooting.md
      - Jupyter:
          - Collaboration: sessions/jupyter/collaboration.md
  - Settings:
      - Monitoring: settings/monitoring.md
      - Tools:
          - General: settings/tools/index.md
          - pure::variants: settings/tools/pure_variants.md
          - Capella:
              - Co-working methods: settings/tools/capella/t4c-git-compare.md
              - TeamForCapella:
                  - Import a model from TeamForCapella: settings/tools/capella/teamforcapella/import/import-from-t4c.md
                  - Export a model to TeamForCapella: settings/tools/capella/teamforcapella/export/export-to-t4c.md
                  - TeamForCapella repository management: settings/tools/capella/teamforcapella/repository-management.md
                  - Update a TeamForCapella based model: settings/tools/capella/teamforcapella/update.md
      - Model sources:
          - Git: settings/model-sources/git.md
      - Alerts:
          - Create an alert: additional/alerts/create.md
          - Delete an alert: additional/alerts/delete.md
  - User Management: users.md
  - Release Notes: release-notes.md
  - About: about.md

repo_url: https://github.com/DSD-DBS/capella-collab-manager
edit_uri: edit/master/docs/user/docs

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - abbr
  - pymdownx.snippets
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false

copyright: Copyright &copy; 2022-2023 DB Netz AG
