# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ease-env
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-ease-env
data:
  GIT_REPO_URL: "{{ .Values.git.url }}"
  GIT_REPO_BRANCH: "{{ .Values.git.branch }}"
  T4C_REPO_HOST: "{{ .Values.t4c.host }}"
  T4C_REPO_PORT: "{{ .Values.t4c.port }}"
  GIT_USERNAME: "{{ .Values.git.username }}"
  GIT_PASSWORD: "{{ .Values.git.password }}"
  T4C_REPO_NAME: "{{ .Values.t4c.repo }}"
  T4C_PROJECT_NAME: "{{ .Values.t4c.project }}"
  T4C_USERNAME: "{{ .Values.t4c.username }}"
  T4C_PASSWORD: "{{ .Values.t4c.password }}"
  T4C_LICENCE_SECRET: "{{ .Values.t4c.licence }}"
  RMT_PASSWORD: "{{ .Values.rdp.password }}"
  T4C_REPOSITORIES: "{{ .Values.t4c.repos }}"
  T4C_SERVER_HOST: "{{ .Values.t4c.host }}"
  T4C_SERVER_PORT: "{{ .Values.t4c.port }}"
  AUTOSTART_CAPELLA: "0"
  DISPLAY: ":10"
  DEBUG: "1"
