# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ease
  labels:
    id: {{ .Release.Name }}-deployment-ease
spec:
  replicas: 1
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-ease
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-ease
    spec:
      volumes:
        - name: {{ .Release.Name }}-ease-script
          configMap:
            name: {{ .Release.Name }}-ease-script
        - name: {{ .Release.Name }}-pyease
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pyease
      containers:
        - name: {{ .Release.Name }}-backend
          image: {{ .Values.docker.registry.internal }}/t4c/client/ease/remote/debug
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-ease-env
          ports:
            - name: rdp
              containerPort: 3389
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-ease-script
              mountPath: /opt/scripts
            - name: {{ .Release.Name }}-pyease
              mountPath: /pyease
          resources:
            limits:
              cpu: "2"
              memory: "6Gi"
            requests:
              cpu: "0.4"
              memory: "1.6Gi"
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
