# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-clusterip
  labels:
    id: {{ .Release.Name }}-service-nginx-clusterip
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-nginx
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
