# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

{{- if eq .Values.cluster.kind "Kubernetes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    id: {{ .Release.Name }}-nginx
  annotations:
    {{ if eq .Values.target "local" }}
    ingress.kubernetes.io/ssl-redirect: "false"
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.general.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nginx-clusterip
                port:
                  number: 80
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-docs
                port:
                  number: 80
          - path: /guacamole
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-guacamole-guacamole
                port:
                  number: 8080
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-prometheus-nginx
                port:
                  name: promui
          {{ if eq .Values.target "local" }}
          - path: /default
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-oauth-mock
                port:
                  number: 8080
          - path: /mock
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mock-clusterip
                port:
                  number: 80
          {{ end }}
{{ end }}
